Add unit tests and rename tortoise.py to tortoise_setup.py
the-riviera-kid/tortoise-lang pull request #16
Opened 2024-07-01 09:27 UTC by CarlaBuongiorno

2024-07-01 12:14 UTC, the-riviera-kid requested changes

2024-07-01 12:14 UTC, the-riviera-kid commented on tortoise_setup.py
>  import sys
I don't understand why the name of this file has been changed. `tortoise_setup.py` implies that this is some internal process, not the entry point of our application.

2024-07-01 12:14 UTC, the-riviera-kid commented on tortoise_interpreter.py
> +    print(command)
Has this `print` been introduced in error? It shouldn't be in here, it makes the surrounding code harder to test.

2024-07-01 12:14 UTC, the-riviera-kid commented on test_tortoise_interpreter.py
> +        ]
This would be more readable if the test code was stored as strings, and then split before passing to `sanitize_program`.

2024-07-01 12:14 UTC, the-riviera-kid commented on test_tortoise_interpreter.py
> +def test_sanatize_program_example_tortoise():
Typo: 'sanitize'

2024-07-01 12:14 UTC, the-riviera-kid commented on test_tortoise_interpreter.py
> +def test_sanatize_program_medium_tortoise():
We should use `@pytest.mark.parametrize` to write more tests of this function more easily.

2024-07-01 12:14 UTC, the-riviera-kid commented on .vscode/settings.json
> +{
The specific settings that you're using in your specific editor should not be committed to the repository.

2024-07-01 12:14 UTC, the-riviera-kid commented on tortoise_interpreter.py
>  def main_tortoise(program):
We will still need to talk about how this gets tested, but we'll get there :+1:

2024-07-01 12:41 UTC, CarlaBuongiorno commented on tortoise_setup.py
>  import sys
I just thought it was a good idea to make it more obvious that this is the main file. Will change it back.

2024-07-01 12:42 UTC, CarlaBuongiorno commented on tortoise_interpreter.py
> +    print(command)
Yes, definitely an error.

2024-07-01 12:50 UTC, CarlaBuongiorno commented on test_tortoise_interpreter.py
> +def test_sanatize_program_example_tortoise():
Oops

2024-07-01 14:29 UTC, the-riviera-kid commented on tortoise_setup.py
>  import sys
If you wanted to make it more obvious that this was the main file, then better names would be `tortoise-main.py`, `run-tortoise.py`, or `entry-point.py`. Anything with `setup` in the title sounds like an internal detail. Good idea though!

2024-07-01 14:32 UTC, the-riviera-kid commented on test_tortoise_interpreter.py
> +    assert sanitized_program == expected
This version is much better. :+1:

2024-07-01 14:47 UTC, CarlaBuongiorno commented on tortoise_setup.py
>  import sys
Good to know

2024-07-02 13:17 UTC, the-riviera-kid commented on test_tortoise_interpreter.py
> +        list_of_strings.append(stuff_to_print)
There we go :)

2024-07-02 13:18 UTC, the-riviera-kid approved these changes

2024-07-02 13:18 UTC, merged